name: Changelog
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: yykamei/actions-update-changelog@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: yykamei/actions-git-push@main
        with:
          commit-message: Update CHANGELOG.md
          branch: update-changelog
      - uses: yykamei/actions-gh-pr-create@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-changelog
          title: Update CHANGELOG.md
          label: chore
          body: |
            *This pull request was automatically created to make CHANGELOG.md the latest*.

            Check the files changes and merge if the changes make sense.
